### ISSUE TITLE
Modification date should have the default timezone

### ISSUE THREAD

**Issue by benwick** [rekalogika/file-metadata#1]
This is not strictly a bug, but more of a suggestion or discussion. The DateTime objects of the modification time are not using the [default timezone of the php environment](https://www.php.net/manual/en/function.date-default-timezone-get.php).

Background:
If someone creates a DateTime object with an empty constructor (`new \DateTimeImmutable()`), the timezone of this object will be the default timezone. If you were to create the DateTime Object like `new \DateTimeImmutable('@' . $timestamp)` or `\DateTimeImmutable::createFromFormat('U', (string) $timestamp)` the timezone won't be set to the default and always fallback to UTC.

Consequences:
- When you look [at this method ](https://github.com/rekalogika/file-metadata/blob/f76eff4747079933ef4a3ecb22eae6c505a35c79/src/Metadata/FileMetadata.php#L95), you can see: It can return DateTime objects with the default timezone (L101, L113) or with UTC (L110). Best case should be always the configured default timezone, so I can easily format it for my environment.
- Reals problems can arise, if you were to safe the modification date as an UTC DateTime object in a database via [Doctrine Embeddable](https://rekalogika.dev/file-bundle/replicating-metadata-in-entities#execution). Doctrine's datetime type will asume the DateTime object is in the default timezone. If it's not, the timestamp will change when the doctrine entity is reconstituted from the database.

Connceted:
- https://github.com/rekalogika/file-association-entity/blob/3140eb62572d9e5b7e6bafa202559ff9f8256530/src/EmbeddedMetadata.php#L148

Solutions:
- `new \DateTimeImmutable('@' . $timestamp, new \DateTimeZone(date_default_timezone_get()))`
- `\DateTimeImmutable::createFromFormat('U', (string) $timestamp, new \DateTimeZone(date_default_timezone_get())`
- `(new \DateTimeImmutable())->setTimestamp($timestamp)`

**Comment by priyadi** [comment]
I wasn't previously aware of this:

> If you were to create the DateTime Object like new \DateTimeImmutable('@' . $timestamp) or \DateTimeImmutable::createFromFormat('U', (string) $timestamp) the timezone won't be set to the default and always fallback to UTC.

I agree that it should return all `DateTime` in the default time zone. Can you submit a PR to [rekalogika/file-src](https://github.com/rekalogika/file-src)?
